//! Deterministic `MiniZinc` emission for the solver-neutral IR.
//!
//! One problem value → one exact `.mzn` text, byte-stable across runs. The
//! emitted model is self-contained (no includes) and prints its witness as
//! `name=value` lines so the runner can parse solver output uniformly.

use std::fmt::Write as _;

use crate::ir::{Constraint, OracleProblem};

/// Emits a complete `MiniZinc` model for the problem.
#[must_use]
pub fn to_minizinc(problem: &OracleProblem) -> String {
    let mut out = String::new();
    let _ = writeln!(
        out,
        "% griff-constraint-lab problem \"{}\" fingerprint {:016x}",
        problem.name(),
        problem.fingerprint()
    );
    let _ = writeln!(out, "% generated by the offline Constraint Lab spike");
    out.push('\n');

    for var in problem.vars() {
        let domain = var
            .domain
            .iter()
            .map(ToString::to_string)
            .collect::<Vec<_>>()
            .join(",");
        let _ = writeln!(out, "var {{{domain}}}: {};", var.name);
    }
    out.push('\n');

    for constraint in problem.constraints() {
        match constraint {
            Constraint::AbsDiffLe { a, b, bound } => {
                let (a, b) = (&problem.vars()[a.0].name, &problem.vars()[b.0].name);
                let _ = writeln!(out, "constraint abs({a} - {b}) <= {bound};");
            }
            Constraint::ForbiddenIntervalClasses {
                var,
                fixed,
                classes,
            } => {
                let name = &problem.vars()[var.0].name;
                let classes = classes
                    .iter()
                    .map(ToString::to_string)
                    .collect::<Vec<_>>()
                    .join(",");
                let _ = writeln!(
                    out,
                    "constraint forall(c in {{{classes}}})((abs({name} - {fixed}) mod 12) != c);"
                );
            }
            Constraint::BandOverlapAtMost {
                vars,
                fixed_lo,
                fixed_hi,
                num,
                den,
            } => {
                let names = vars
                    .iter()
                    .map(|v| problem.vars()[v.0].name.clone())
                    .collect::<Vec<_>>()
                    .join(",");
                let _ = writeln!(
                    out,
                    "constraint let {{ var int: b_lo = min([{names}]);\n\
                     \x20                var int: b_hi = max([{names}]);\n\
                     \x20                var int: i_lo = max({fixed_lo}, b_lo);\n\
                     \x20                var int: i_hi = min({fixed_hi}, b_hi);\n\
                     \x20                var int: ov = max(0, i_hi - i_lo);\n\
                     \x20                var int: narrower = min({fixed_hi} - {fixed_lo}, b_hi - b_lo) }} in\n\
                     \x20 if narrower == 0 then i_hi < i_lo else ov * {den} <= narrower * {num} endif;"
                );
            }
        }
    }
    out.push('\n');

    let _ = writeln!(out, "solve satisfy;");
    let mut pieces: Vec<String> = Vec::new();
    for var in problem.vars() {
        pieces.push(format!("\"{}=\"", var.name));
        pieces.push(format!("show({})", var.name));
        pieces.push("\"\\n\"".to_string());
    }
    let _ = writeln!(out, "output [{}];", pieces.join(", "));
    out
}
